config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :posters
    resources :lighthouses

    root to: "users#index"
  end

  devise_for :users
  resources :posters
  resources :lighthouses

  root to: "posters#home"
  get "contact" => "contact#new", :as => "contact"
  post "contact" => "contact#create"
  get '/.well-known/acme-challenge/:id' => 'pages#letsencrypt'

  scope "api", defaults: {format: :json} do
    resources :posters
    resources :lighthouses
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lighthouse.rb
class Lighthouse < ApplicationRecord
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/poster.rb
class Poster < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      redirect_to new_user_session_path unless user_signed_in?
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/lighthouses_controller.rb
module Admin
  class LighthousesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Lighthouse.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Lighthouse.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/posters_controller.rb
module Admin
  class PostersController < Admin::ApplicationController
    def find_resource(param) 
      Poster.find_by!(slug: param)
    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Thanks! I got your message, I'll get back to you as soon as I can!")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/lighthouses_controller.rb
class LighthousesController < ApplicationController
  before_action :set_lighthouse, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /lighthouses
  def index
    @lighthouses = Lighthouse.all
    @lighthouse_image_host = lighthouse_image_host
    @geojson = Array.new

    @lighthouses.each do |lighthouse|
      lighthouse_image_path = URI.parse(lighthouse.instagram.to_s).path

      @geojson << {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [lighthouse.longitude, lighthouse.latitude]
        },
        properties: {
          name: lighthouse.title,
          instagram: "#{lighthouse_image_host}" + lighthouse_image_path.to_s
        }
      }
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @geojson }
    end
  end

  # GET /lighthouses/1
  def show
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @lighthouse }
    end
  end

  # GET /lighthouses/new
  def new
    @lighthouse = Lighthouse.new
  end

  # GET /lighthouses/1/edit
  def edit
  end

  # POST /lighthouses
  def create
    @lighthouse = Lighthouse.new(lighthouse_params)

    if @lighthouse.save
      redirect_to @lighthouse, notice: 'Lighthouse was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /lighthouses/1
  def update
    if @lighthouse.update(lighthouse_params)
      redirect_to @lighthouse, notice: 'Lighthouse was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /lighthouses/1
  def destroy
    @lighthouse.destroy
    redirect_to lighthouses_url, notice: 'Lighthouse was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lighthouse
      @lighthouse = Lighthouse.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lighthouse_params
      params.require(:lighthouse).permit(:title, :location)
    end

    def lighthouse_image_host
      "https://jenny.smharley.com"
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def letsencrypt
    render text: "0RXca7YdxUV8aMVSw2jeqYlab3I3PYSsfleKgty_v0U.1eG2CMTjNPvpGKAvliDuItHt-gz7Xqq7XairJRxbv7w"
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  before_action :set_poster, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :home]

  # GET /
  def home
    @posters = Poster.last(8).reverse
    @poster_thumb_host_url = poster_thumb_host_url
  end

  # GET /posters
  def index
    @posters = Poster.all.order(:poster_date).reverse
    @poster_thumb_host_url = poster_thumb_host_url

    respond_to do |format|
      format.html
      format.json { render json: @posters }
    end
  end

  # GET /posters/1
  def show
    @poster_host_url = poster_host_url

    respond_to do |format|
      format.html
      format.json { render json: @poster }
    end
  end

  # GET /posters/new
  def new
    @poster = Poster.new
  end

  # GET /posters/1/edit
  def edit
  end

  # POST /posters
  def create
    @poster = Poster.new(poster_params)

    if @poster.save
      redirect_to @poster, notice: 'Poster was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /posters/1
  def update
    if @poster.update(poster_params)
      redirect_to @poster, notice: 'Poster was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /posters/1
  def destroy
    @poster.destroy
    redirect_to posters_url, notice: 'Poster was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def poster_host_url
      "https://jenny.smharley.com/posters/large/"
    end

    def poster_thumb_host_url
      "https://jenny.smharley.com/posters/thumbs/"
    end

    def set_poster
      @poster = Poster.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def poster_params
      params.require(:poster).permit(:name, :slug, :poster_date, :image_url, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.slim
- if flash.any?
  .flash
    - flash.each do |key, value|
      div class=("flash-#{key}")
        = value

app/views/application/_footer.slim
footer
  .footer
    .footer-logo
      = inline_svg "logo-mini.svg"

    .footer-copyright
      a.footer-link href="/"
        | &copy; #{Date.current.year} Jen Harley

    .footer-links
      a.footer-link href="/posters" Posters
      a.footer-link href="/lighthouses" Lighthouses
      a.footer-link href="http://blog.jenharley.com" Blog
      a.footer-link href="/contact" Contact

    .footer-social
      a.footer-social-link.footer-social-link--twitter href="https://twitter.com/harleyo"
        = inline_svg "twitter.svg"
      a.footer-social-link.footer-social-link--instagram href="https://instagram.com/jenmharley/"
        = inline_svg "instagram.svg"
      a.footer-social-link.footer-social-link--vimeo href="https://vimeo.com/jenhar"
        = inline_svg "vimeo.svg"
      a.footer-social-link.footer-social-link--dribbble href="https://dribbble.com/jenhar"
        = inline_svg "dribbble.svg"

app/views/application/_header.slim
nav.nav.nav--centered
  .nav__wrapper
    a.nav__logo--mobile href="/"
      = inline_svg "logo-mini.svg"
    a.nav__menu-button href="javascript:void(0)" data-js='menu-toggle'
      | MENU
    ul.nav__list data-js='menu'
      li.nav__list-item
        a.nav__link href="/posters"
          | Posters
      li.nav__list-item
        a.nav__link href="/lighthouses"
          | Lighthouses
      li.nav__list-item.nav__logo
        a.nav__link href="/"
          = inline_svg "logo-mini.svg"
      li.nav__list-item
        a.nav__link href="//blog.jenharley.com"
          | Blog
      li.nav__list-item
        a.nav__link href="/contact" target="_self"
          | Contact
      - if user_signed_in?
        = button_to "Sign out", destroy_user_session_path,
          method: :delete

app/views/application/_javascript.html.slim
= javascript_include_tag :application

= yield :javascript

app/views/application/_logo_mini.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve">
<g>
  <g>
    <path fill="#FFFFFF" d="M12.6,30.6c-1.8,1.3-3.1,3.3-3.1,5.9c0,2.6,0.6,4.6,1.6,6c1.6,2.3,4.2,3.2,6.6,3.2c3.9,0,8.2-2.3,8.2-9.2
      V29h-7.3C15.9,29,14,29.7,12.6,30.6z"/>
    <path fill="#FFFFFF" d="M30,0C13.4,0,0,13.4,0,30c0,16.6,13.4,30,30,30c16.6,0,30-13.4,30-30C60,13.4,46.6,0,30,0z M43.4,29v23.5
      H41V29H28.3v7.5c0,8.5-5.5,11.6-10.6,11.6c-5,0-10.3-2.8-10.6-10.8l0.1-2c0.7-4.5,3.9-8.7,11.4-8.7h7.3V9.8h-9.5V7.5h12v19H41
      v-9.5h2.3l0,9.6h9.6V29H43.4z"/>
  </g>
</g>
</svg>

app/views/contact/new.html.slim
- content_for :title, "Contact Jen Harley"

.contact
  h2.contact-header
    | Contact
  p
    | If you want to work together, or just say Hey, fill out the form and I'll get back to you!
  .contact-form
    = form_for @message, url: contact_path do |form|
      .field.sky-label
        = form.label :name
        = form.text_field :name
      .field.sky-label
        = form.label :email
        = form.text_field :email
      .field.sky-label
        = form.label :subject
        = form.text_field :subject
      .field.sky-label
        = form.label :body
        = form.text_area :body
      = form.submit "Send message"

app/views/layouts/application.slim
doctype html
html
head
  meta charset="utf-8"
  meta name="ROBOTS" content="NOODP"
  meta name="viewport" content="initial-scale=1"
  title
    - if content_for?(:title)
      = yield :title
    - else
      = title
  link href="/favicon.ico" rel="icon" type="image/png"

  = stylesheet_link_tag :application, media: "all"
  link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Merriweather:300,700,700italic,300italic|Open+Sans:700,400"

  script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js'
  link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet'

  link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""

  script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""
  script src='https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.4/leaflet.markercluster.js'
  link href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.4/MarkerCluster.css' rel='stylesheet'
  link href='https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.0.4/MarkerCluster.Default.css' rel='stylesheet'
  script src="//rawgit.com/mapbox/mapbox-gl-leaflet/master/leaflet-mapbox-gl.js"

  = csrf_meta_tags

body(class=body_class)
  = render "flashes"
  = render "header"

  main.main role="main"
    = yield

  = render "footer"
  = render "javascript"

app/views/lighthouses/_form.html.slim
= form_for @lighthouse do |f|
  - if @lighthouse.errors.any?
    #error_explanation
      h2 = "#{pluralize(@lighthouse.errors.count, "error")} prohibited this lighthouse from being saved:"
      ul
        - @lighthouse.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description, as: :textarea
  .field
    = f.label :instagram
    = f.text_field :instagram
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .actions = f.submit

app/views/lighthouses/edit.html.slim
h1 Editing lighthouse

== render 'form'

=> link_to 'Show', @lighthouse
'|
=< link_to 'Back', lighthouses_path

app/views/lighthouses/index.html.slim
#map

app/views/lighthouses/new.html.slim
h1 New lighthouse

== render 'form'

= link_to 'Back', lighthouses_path

app/views/lighthouses/show.html.slim
p#notice = notice

p
  strong Title:
  = @lighthouse.title
p
  strong Latitude:
  = @lighthouse.latitude
p
  strong Location:
  = @lighthouse.longitude
p
  strong Instagram:
  = @lighthouse.instagram

=> link_to 'Edit', edit_lighthouse_path(@lighthouse)
'|
=< link_to 'Back', lighthouses_path

app/views/pages/letsencrypt.html.erb
0RXca7YdxUV8aMVSw2jeqYlab3I3PYSsfleKgty_v0U.1eG2CMTjNPvpGKAvliDuItHt-gz7Xqq7XairJRxbv7w

app/views/pages/store.html.slim
- content_for :extra_body_classes, "store-page"
- content_for :title, "Jen Harley's Store"

.store
  | More coming soon!

app/views/partials/_header.html.slim
nav.nav.nav--centered
  .nav__wrapper
    a.nav__logo--mobile href="/"
      = render "partials/logo_mini"
    a.nav__menu-button href="javascript:void(0)" data-js='menu-toggle'
      | MENU
    ul.nav__list data-js='menu'
      li.nav__list-item
        a.nav__link href="/posters"
          | Posters
      li.nav__list-item
        a.nav__link href="//blog.jenharley.com"
          | Blog
      li.nav__list-item.nav__logo
        a.nav__link href="/"
          = render "partials/logo"
      li.nav__list-item
        a.nav__link href="/about"
          | About
      li.nav__list-item
        a.nav__link href="/contact" target="_self"
          | Contact

app/views/partials/_logo--mini.html.erb
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
   viewBox="0 0 60 60" enable-background="new 0 0 60 60" xml:space="preserve">
<g>
  <g>
    <path fill="#FFFFFF" d="M12.6,30.6c-1.8,1.3-3.1,3.3-3.1,5.9c0,2.6,0.6,4.6,1.6,6c1.6,2.3,4.2,3.2,6.6,3.2c3.9,0,8.2-2.3,8.2-9.2
      V29h-7.3C15.9,29,14,29.7,12.6,30.6z"/>
    <path fill="#FFFFFF" d="M30,0C13.4,0,0,13.4,0,30c0,16.6,13.4,30,30,30c16.6,0,30-13.4,30-30C60,13.4,46.6,0,30,0z M43.4,29v23.5
      H41V29H28.3v7.5c0,8.5-5.5,11.6-10.6,11.6c-5,0-10.3-2.8-10.6-10.8l0.1-2c0.7-4.5,3.9-8.7,11.4-8.7h7.3V9.8h-9.5V7.5h12v19H41
      v-9.5h2.3l0,9.6h9.6V29H43.4z"/>
  </g>
</g>
</svg>

app/views/posters/_form.html.erb
<%= form_with(model: poster, local: true) do |form| %>
  <% if poster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poster.errors.count, "error") %> prohibited this poster from being saved:</h2>

      <ul>
      <% poster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :poster_name %>
  </div>

  <div class="field">
    <%= form.label :slug %>
    <%= form.text_field :slug, id: :poster_slug %>
  </div>

  <div class="field">
    <%= form.label :poster_date %>
    <%= form.date_select :poster_date, id: :poster_poster_date %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :poster_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posters/_poster.html.slim
= link_to poster_path(poster), class: "poster-list-link" do
  = image_tag poster_thumb_host_url + poster.image_url, class: "poster-image"

  .poster-meta
    h2.poster-name
      = poster.name
    p.poster-date
      = poster.poster_date.strftime('%B %e, %Y')

app/views/posters/edit.html.erb
<h1>Editing Poster</h1>

<%= render 'form', poster: @poster %>

<%= link_to 'Show', @poster %> |
<%= link_to 'Back', posters_path %>

app/views/posters/home.html.slim
.home
  figure.hero.hero--home
    = render "home_hero"

  h2.page-heading
    | Recent Posters

  ol.poster-list
    - @posters.each do |poster|
      li.poster-list-item
        = render partial: "posters/poster", locals: { poster: poster,
          poster_thumb_host_url: @poster_thumb_host_url }

  .blog-articles data-blog=""
    h2.page-heading
      | Recent Blog Articles

app/views/posters/index.html.slim
- content_for :title, "Recent Posters - Jen Harley"

h1.page-heading
  | Recent Posters

ol.poster-list
  - @posters.each do |poster|
    li.poster-list-item
      = render partial: "posters/poster", locals: { poster: poster,
        poster_thumb_host_url: @poster_thumb_host_url }

app/views/posters/new.html.erb
<h1>New Poster</h1>

<%= render 'form', poster: @poster %>

<%= link_to 'Back', posters_path %>

app/views/posters/show.html.slim
- content_for :title, "#{@poster.name} by Jen Harley"

.poster
  .poster-meta
    h1.poster-name
      = @poster.name
    p.poster-date
      = @poster.poster_date.strftime('%B %e, %Y')

  .poster-image
    = image_tag @poster_host_url + @poster.image_url